### PR TITLE
Weeb commands (including flag arguments and non-cnext commands)

### PR DESCRIPTION
**Pull request by tech6hutch**

### CODE REVIEW

**Comment by tech6hutch** [comment]
whoa, calm down todo bot

**Comment by Godson777** [comment]
todo bot was really excited lol

**Comment by tech6hutch** [comment]
Why did it post the same TODO again

**Comment by Godson777** [comment]
todo REALLY wants you to take care of that todo LOL

**Comment by Godson777** [comment]
I think todo-bot is happy now LOL

**Comment by Godson777** [comment]
You could just remove the `Console.WriteLine()`s and invert your `if` statement. `if (config.WeebToken != null) CommandsNext.RegisterCommands<WeebCommands>();`

**Comment by tech6hutch** [comment]
I could, but I like having the logs for whether optional command categories are being loaded. That would be the easiest solution, tho.

**Comment by Godson777** [comment]
Then maybe it's not such a bad idea to have it appear on multiple shards. 
image
Just move the event listeners up in the code, and then just output to the logger instead of to console directly.
`this.Discord.DebugLogger.LogMessage(LogLevel.Info, LOGTAG, "NOT registering weeb commands because no token was found >:(", DateTime.Now);`

**Comment by tech6hutch** [comment]
Yeahhhhhh, but it's more of a one time thing, and every shard will do the exact same thing. Not a big deal tho, I'll do that.

**Comment by tech6hutch** [comment]
I'm not currently using the HiddenParam attribute, but it's useful for flag args, if they're used with any regular command in the future.

**Pull request merged**
